//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homesfy.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuilderProjectFloorPlan
    {
        public decimal BuilderProjFloorPlanID { get; set; }
        public Nullable<decimal> BuilderProjectConfigId { get; set; }
        public string FloorPlanName { get; set; }
        public string FloorPlanSmallImage { get; set; }
        public string FloorPlanBigImage { get; set; }
    
        public virtual BuilderProjectConfig BuilderProjectConfig { get; set; }
    }
}
