//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homesfy.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuilderProjectConfig
    {
        public BuilderProjectConfig()
        {
            this.BuilderProjectFloorPlans = new HashSet<BuilderProjectFloorPlan>();
            this.BuilderProjectSubConfigs = new HashSet<BuilderProjectSubConfig>();
        }
    
        public decimal BuilderProjectConfigId { get; set; }
        public Nullable<decimal> BuilderProjectId { get; set; }
        public Nullable<decimal> mPropConfigId { get; set; }
        public Nullable<decimal> ProjectConfigAreaMin { get; set; }
        public Nullable<decimal> ProjectConfigAreaMax { get; set; }
        public Nullable<decimal> ProjectConfigMinPrice { get; set; }
        public Nullable<decimal> ProjectConfigMaxPrice { get; set; }
    
        public virtual mBuilderProject mBuilderProject { get; set; }
        public virtual mPropConfig mPropConfig { get; set; }
        public virtual ICollection<BuilderProjectFloorPlan> BuilderProjectFloorPlans { get; set; }
        public virtual ICollection<BuilderProjectSubConfig> BuilderProjectSubConfigs { get; set; }
    }
}
