//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homesfy.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Builder_EscalationMatrix
    {
        public decimal BuilderEscalationID { get; set; }
        public Nullable<decimal> BuilderId { get; set; }
        public string Escaltion1Name { get; set; }
        public Nullable<decimal> Escaltion1ContactNo { get; set; }
        public string Escaltion1EmailID { get; set; }
        public string Escaltion2Name { get; set; }
        public Nullable<decimal> Escaltion2ContactNo { get; set; }
        public string Escaltion2EmailID { get; set; }
        public string Escaltion3Name { get; set; }
        public Nullable<decimal> Escaltion3ContactNo { get; set; }
        public string Escaltion3EmailID { get; set; }
    }
}
