//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homesfy.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocalityDetail
    {
        public LocalityDetail()
        {
            this.LocalityBlocks = new HashSet<LocalityBlock>();
            this.LocalityDetailsCommutes = new HashSet<LocalityDetailsCommute>();
            this.LocalityKeyHighLights = new HashSet<LocalityKeyHighLight>();
            this.LocalityGreatPlaces = new HashSet<LocalityGreatPlace>();
            this.LocalityTags = new HashSet<LocalityTag>();
        }
    
        public decimal LocalityDetailsId { get; set; }
        public decimal mLocalityID { get; set; }
        public string GoogleMap { get; set; }
        public string GoogleMapDescription { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<decimal> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<decimal> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual ICollection<LocalityBlock> LocalityBlocks { get; set; }
        public virtual ICollection<LocalityDetailsCommute> LocalityDetailsCommutes { get; set; }
        public virtual ICollection<LocalityKeyHighLight> LocalityKeyHighLights { get; set; }
        public virtual ICollection<LocalityGreatPlace> LocalityGreatPlaces { get; set; }
        public virtual ICollection<LocalityTag> LocalityTags { get; set; }
    }
}
