//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homesfy.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocalityTripRequest
    {
        public decimal TripId { get; set; }
        public decimal UserId { get; set; }
        public Nullable<decimal> UserTypeId { get; set; }
        public Nullable<decimal> LocalityId { get; set; }
        public Nullable<System.DateTime> VisitDateTime { get; set; }
        public Nullable<decimal> PickUpLocation { get; set; }
        public Nullable<decimal> DropLocation { get; set; }
        public Nullable<decimal> NoOfPeople { get; set; }
        public Nullable<decimal> Propscout { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<decimal> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreadtedDate { get; set; }
        public Nullable<decimal> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
