//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homesfy.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocalityBlock
    {
        public LocalityBlock()
        {
            this.LocalityBlockGalleries = new HashSet<LocalityBlockGallery>();
        }
    
        public decimal LocalityBlockId { get; set; }
        public Nullable<decimal> mLocalityId { get; set; }
        public string BlockHeading { get; set; }
        public string BlockTitle { get; set; }
        public string BlockSubTitle { get; set; }
        public string BlockDesc { get; set; }
    
        public virtual LocalityDetail LocalityDetail { get; set; }
        public virtual mLocality mLocality { get; set; }
        public virtual ICollection<LocalityBlockGallery> LocalityBlockGalleries { get; set; }
    }
}
