//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homesfy.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class mBuilding
    {
        public mBuilding()
        {
            this.BuildingGalleries = new HashSet<BuildingGallery>();
        }
    
        public decimal mBuildingID { get; set; }
        public decimal SocietyId { get; set; }
        public decimal LocalityId { get; set; }
        public Nullable<decimal> BuilderId { get; set; }
        public string BuildingName { get; set; }
        public string BuildingShortDesc { get; set; }
        public string BuildingLongDesc { get; set; }
        public Nullable<decimal> BuildingAge { get; set; }
        public Nullable<decimal> NoOfFloors { get; set; }
        public Nullable<decimal> NoOfAppartments { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<decimal> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<decimal> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual ICollection<BuildingGallery> BuildingGalleries { get; set; }
        public virtual mLocality mLocality { get; set; }
        public virtual mSociety mSociety { get; set; }
    }
}
