//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homesfy.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class mBuilderProject
    {
        public mBuilderProject()
        {
            this.BuilderProjectConfigs = new HashSet<BuilderProjectConfig>();
            this.BuilderProjExternalAmenities = new HashSet<BuilderProjExternalAmenity>();
            this.BuilderProjGalleries = new HashSet<BuilderProjGallery>();
            this.BuilderProjInternalAmenities = new HashSet<BuilderProjInternalAmenity>();
        }
    
        public decimal BuilderProjectId { get; set; }
        public Nullable<decimal> BuilderId { get; set; }
        public Nullable<decimal> mPropertyCategoryId { get; set; }
        public string BuilderProjectHeading { get; set; }
        public string BuilderProjectName { get; set; }
        public string ShortDesc { get; set; }
        public string LongDesc { get; set; }
        public Nullable<decimal> BuilderProjectLocationID { get; set; }
        public string ProjectStatus { get; set; }
        public string InternalAmenitiesHeading { get; set; }
        public string InternalAmenitiesDesc { get; set; }
        public string MetaTitle { get; set; }
        public string MetaDescription { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> PossesionDate { get; set; }
        public string ThumbnailImage { get; set; }
        public string LinkedBlog { get; set; }
        public string GoogleMap { get; set; }
        public string LocationMap { get; set; }
        public string MasterPlan { get; set; }
        public Nullable<decimal> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<decimal> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsPublished { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual Builder Builder { get; set; }
        public virtual ICollection<BuilderProjectConfig> BuilderProjectConfigs { get; set; }
        public virtual ICollection<BuilderProjExternalAmenity> BuilderProjExternalAmenities { get; set; }
        public virtual ICollection<BuilderProjGallery> BuilderProjGalleries { get; set; }
        public virtual ICollection<BuilderProjInternalAmenity> BuilderProjInternalAmenities { get; set; }
        public virtual mPropertyCategory mPropertyCategory { get; set; }
    }
}
