//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homesfy.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class mCountry
    {
        public mCountry()
        {
            this.mStates = new HashSet<mState>();
        }
    
        public decimal mCountryId { get; set; }
        public string CountryName { get; set; }
        public string ISOCode { get; set; }
        public string CurrencyCode { get; set; }
        public Nullable<long> Status { get; set; }
        public Nullable<decimal> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<decimal> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual ICollection<mState> mStates { get; set; }
    }
}
