//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homesfy.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class mCrmLeadPurpose
    {
        public mCrmLeadPurpose()
        {
            this.CrmLeadDetails = new HashSet<CrmLeadDetail>();
        }
    
        public decimal crmLeadPurposeId { get; set; }
        public string LeadPurposeName { get; set; }
        public Nullable<decimal> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<decimal> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual ICollection<CrmLeadDetail> CrmLeadDetails { get; set; }
    }
}
