//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homesfy.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class mInternalAmenity
    {
        public mInternalAmenity()
        {
            this.BuilderProjInternalAmenities = new HashSet<BuilderProjInternalAmenity>();
        }
    
        public decimal InternalAmenitiesID { get; set; }
        public string InternalAmenitiesName { get; set; }
        public Nullable<decimal> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<decimal> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<BuilderProjInternalAmenity> BuilderProjInternalAmenities { get; set; }
    }
}
