//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homesfy.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class mLocality
    {
        public mLocality()
        {
            this.LocalityBlocks = new HashSet<LocalityBlock>();
            this.LocalityDetailsCommutes = new HashSet<LocalityDetailsCommute>();
            this.LocalityGalleries = new HashSet<LocalityGallery>();
            this.LocalityGreatPlaces = new HashSet<LocalityGreatPlace>();
            this.LocalityKeyHighLights = new HashSet<LocalityKeyHighLight>();
            this.LocalitySuggestions = new HashSet<LocalitySuggestion>();
            this.LocalityTags = new HashSet<LocalityTag>();
            this.mBuildings = new HashSet<mBuilding>();
            this.PropscoutWorkAreas = new HashSet<PropscoutWorkArea>();
            this.mSocieties = new HashSet<mSociety>();
        }
    
        public decimal mLocalityId { get; set; }
        public Nullable<decimal> mCityId { get; set; }
        public string LocalityName { get; set; }
        public Nullable<decimal> LocalityZipCode { get; set; }
        public string LocalityThumbnail { get; set; }
        public string LocalityShortDesc { get; set; }
        public string LocalityLongDesc { get; set; }
        public Nullable<decimal> PropMinimumPrice { get; set; }
        public Nullable<decimal> PropMaximumPrice { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<decimal> CreadtedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<decimal> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual ICollection<LocalityBlock> LocalityBlocks { get; set; }
        public virtual ICollection<LocalityDetailsCommute> LocalityDetailsCommutes { get; set; }
        public virtual ICollection<LocalityGallery> LocalityGalleries { get; set; }
        public virtual ICollection<LocalityGreatPlace> LocalityGreatPlaces { get; set; }
        public virtual ICollection<LocalityKeyHighLight> LocalityKeyHighLights { get; set; }
        public virtual ICollection<LocalitySuggestion> LocalitySuggestions { get; set; }
        public virtual ICollection<LocalityTag> LocalityTags { get; set; }
        public virtual ICollection<mBuilding> mBuildings { get; set; }
        public virtual mCity mCity { get; set; }
        public virtual ICollection<PropscoutWorkArea> PropscoutWorkAreas { get; set; }
        public virtual ICollection<mSociety> mSocieties { get; set; }
    }
}
