//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homesfy.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class mNeighbourHoodTag
    {
        public mNeighbourHoodTag()
        {
            this.mCategoryOfExternalAmenities = new HashSet<mCategoryOfExternalAmenity>();
        }
    
        public decimal mNeighbourHoodId { get; set; }
        public Nullable<decimal> TagName { get; set; }
        public string TagDescription { get; set; }
        public Nullable<decimal> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDatetime { get; set; }
        public Nullable<decimal> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
    
        public virtual ICollection<mCategoryOfExternalAmenity> mCategoryOfExternalAmenities { get; set; }
    }
}
