//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homesfy.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class mPriceRange
    {
        public decimal PriceConfigId { get; set; }
        public Nullable<decimal> PriceMin { get; set; }
        public Nullable<decimal> PriceMax { get; set; }
    }
}
