//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homesfy.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class mSocietyGallery
    {
        public decimal mSocietyGalleryId { get; set; }
        public Nullable<decimal> mSocietyId { get; set; }
        public string SocietyImage { get; set; }
        public string ImageDescription { get; set; }
    
        public virtual mSociety mSociety { get; set; }
    }
}
