//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homesfy.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public decimal ProjectId { get; set; }
        public string ProjectName { get; set; }
        public string GroupName { get; set; }
        public Nullable<decimal> CountryId { get; set; }
        public Nullable<decimal> StateId { get; set; }
        public Nullable<decimal> CityId { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> BuilderId { get; set; }
        public Nullable<decimal> NoOfProperties { get; set; }
        public string ProjectUrl { get; set; }
        public string LinkedBlog { get; set; }
        public string projectImagePath { get; set; }
        public Nullable<bool> IsThumbnail { get; set; }
        public Nullable<decimal> ProjectPropscout { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<decimal> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<decimal> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
