//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homesfy.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prop_Review
    {
        public decimal PropReviewId { get; set; }
        public Nullable<decimal> PropListId { get; set; }
        public string PropReviewDesc { get; set; }
        public Nullable<System.DateTime> PropReviewDatetime { get; set; }
    }
}
