//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homesfy.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropBlog
    {
        public decimal PropBlogId { get; set; }
        public Nullable<decimal> PropListId { get; set; }
        public Nullable<decimal> BuilderId { get; set; }
        public string BlogName { get; set; }
        public string BlogDesc { get; set; }
    }
}
