//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homesfy.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prop_List
    {
        public decimal PropListId { get; set; }
        public Nullable<decimal> PropCatId { get; set; }
        public Nullable<decimal> BuildingId { get; set; }
        public Nullable<decimal> SocietyId { get; set; }
        public Nullable<decimal> LocationId { get; set; }
        public Nullable<decimal> UserProfileId { get; set; }
        public string PurposeOfListing { get; set; }
        public string ProjectName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string PropListBlock { get; set; }
        public string PropListHouseNumber { get; set; }
        public string BriefDescriptionofPRoperty { get; set; }
        public string BuiltUpArea { get; set; }
        public Nullable<decimal> NoOfBedRooms { get; set; }
        public Nullable<decimal> NoOfBathRooms { get; set; }
        public Nullable<decimal> Balconies { get; set; }
        public Nullable<decimal> PropValue { get; set; }
        public Nullable<decimal> PriceConfigId { get; set; }
        public Nullable<bool> Isnegotable { get; set; }
        public Nullable<bool> CostWithRegistrationCost { get; set; }
        public string ListingCategory { get; set; }
        public string IsStatus { get; set; }
        public string IsPublished { get; set; }
        public Nullable<decimal> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<decimal> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
